title: "Hesam Haddad - DemoVersion"
description: "Hesam Haddad, Machine Learning Engineer, showcasing projects and posts on AI and ML"
baseurl: ""
url: "https://demoversion.dev"

theme: null

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/